version: "3"

services:
  base:
    build: ./base
    image: bde2020/hadoop-base:2.0.0-hadoop3.1.1-java8-py3

  namenode:
    build: ./namenode
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.1.1-java8-py3
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    ports:
      - "9800:9000"
      - "9870:9870"
    env_file:
      - ./hadoop.env

  datanode1:
    build: ./datanode
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.1-java8-py3
    container_name: datanode1
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode

  datanode2:
    build: ./datanode
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.1-java8-py3
    container_name: datanode2
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode

  datanode3:
    build: ./datanode
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.1-java8-py3
    container_name: datanode3
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode

  resourcemanager:
    build: ./resourcemanager
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.1.1-java8-py3
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864"
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3

  nodemanager1:
    build: ./nodemanager
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.1.1-java8-py3
    container_name: nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
      - resourcemanager

  historyserver:
    build: ./historyserver
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.1.1-java8-py3
    container_name: historyserver
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
      - resourcemanager

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
  hadoop_historyserver:
